// <auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;



namespace DataMapper.Migrations
{
    public partial class ContractEntity : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Abonament_Client_ClientId",
                table: "Abonament");

            migrationBuilder.DropIndex(
                name: "IX_Abonament_ClientId",
                table: "Abonament");

            migrationBuilder.DropColumn(
                name: "ClientId",
                table: "Abonament");

            migrationBuilder.CreateTable(
                name: "Contract",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    ClientId = table.Column<Guid>(nullable: true),
                    AbonamentId = table.Column<Guid>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Contract", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Contract_Abonament_AbonamentId",
                        column: x => x.AbonamentId,
                        principalTable: "Abonament",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Contract_Client_ClientId",
                        column: x => x.ClientId,
                        principalTable: "Client",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Contract_AbonamentId",
                table: "Contract",
                column: "AbonamentId");

            migrationBuilder.CreateIndex(
                name: "IX_Contract_ClientId",
                table: "Contract",
                column: "ClientId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Contract");

            migrationBuilder.AddColumn<Guid>(
                name: "ClientId",
                table: "Abonament",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Abonament_ClientId",
                table: "Abonament",
                column: "ClientId");

            migrationBuilder.AddForeignKey(
                name: "FK_Abonament_Client_ClientId",
                table: "Abonament",
                column: "ClientId",
                principalTable: "Client",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
