// <auto-generated/>
using System;
using System.Diagnostics.CodeAnalysis;

namespace DataMapper
{
    [ExcludeFromCodeCoverage]
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
