// <auto-generated/>
using DataMapper.Interfaces;
using DataMapper;
using System;
using DistribuitorServiciiMobile.Models;
using ServiceLayer.Controllers;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics.CodeAnalysis;

namespace ServiceLayer
{
    [ExcludeFromCodeCoverage]
    class Program
    {
        static void Main(string[] args)
        {
            
        }
    }
}
